### ISSUE TITLE
IdeaMantis plugin deadlocks IDE 

### ISSUE THREAD

**Issue by L3if** [domjos1994/ideaMantis#16]
STR:
Install CLion (any of 2021.1 - 2021.3)
Install IdeaMantis plugin
Open any project
Open Mantis-BT toolwindow

Result:
UI Froze, only kill helps

"AWT-EventQueue-0" prio=0 tid=0x0 nid=0x0 runnable
     java.lang.Thread.State: RUNNABLE

	at java.base@11.0.11/sun.nio.cs.UTF_8$Encoder.encodeLoop(UTF_8.java:564)
	at java.base@11.0.11/java.nio.charset.CharsetEncoder.encode(CharsetEncoder.java:576)
	at java.base@11.0.11/sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:292)
	at java.base@11.0.11/sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:281)
	at java.base@11.0.11/sun.nio.cs.StreamEncoder.write(StreamEncoder.java:125)
	at java.base@11.0.11/sun.nio.cs.StreamEncoder.write(StreamEncoder.java:113)
	at java.base@11.0.11/java.io.OutputStreamWriter.write(OutputStreamWriter.java:190)
	at org.kxml2.io.KXmlSerializer.writeEscaped(Unknown Source)
	at org.kxml2.io.KXmlSerializer.check(Unknown Source)
	at org.kxml2.io.KXmlSerializer.startTag(Unknown Source)
	at org.ksoap2.SoapEnvelope.write(Unknown Source)
	at org.ksoap2.transport.Transport.createRequestData(Unknown Source)
	at org.ksoap2.transport.HttpTransportSE.call(Unknown Source)
	at de.domjos.ideaMantis.soap.MantisSoapAPI.executeQueryAndGetSoapObject(MantisSoapAPI.java:1233)
	at de.domjos.ideaMantis.soap.MantisSoapAPI.getTags(MantisSoapAPI.java:911)
	at de.domjos.ideaMantis.ui.IdeaMantisIssues.addAutoCompletion(IdeaMantisIssues.java:1790)
	at de.domjos.ideaMantis.ui.IdeaMantisIssues.createToolWindowContent(IdeaMantisIssues.java:1165)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.createContentIfNeeded$intellij_platform_ide_impl(ToolWindowImpl.kt:524)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.scheduleContentInitializationIfNeeded$intellij_platform_ide_impl(ToolWindowImpl.kt:503)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.doShowWindow(ToolWindowManagerImpl.kt:1016)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.showToolWindowImpl(ToolWindowManagerImpl.kt:962)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.activateToolWindow(ToolWindowManagerImpl.kt:665)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.activateToolWindow$default(ToolWindowManagerImpl.kt:643)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.activated$intellij_platform_ide_impl(ToolWindowManagerImpl.kt:2027)
	at com.intellij.openapi.wm.impl.StripeButton.lambda$new$0(StripeButton.java:68)
	at com.intellij.openapi.wm.impl.StripeButton$$Lambda$1965/0x000000080146c840.actionPerformed(Unknown Source)
	at java.desktop@11.0.11/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop@11.0.11/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop@11.0.11/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop@11.0.11/javax.swing.JToggleButton$ToggleButtonModel.setPressed(JToggleButton.java:401)
	at java.desktop@11.0.11/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:270)
	at java.desktop@11.0.11/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop@11.0.11/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop@11.0.11/java.awt.Component.processMouseEvent(Component.java:6652)
	at java.desktop@11.0.11/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
	at com.intellij.openapi.wm.impl.StripeButton.processMouseEvent(StripeButton.java:329)
	at java.desktop@11.0.11/java.awt.Component.processEvent(Component.java:6417)
	at java.desktop@11.0.11/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop@11.0.11/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop@11.0.11/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop@11.0.11/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop@11.0.11/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop@11.0.11/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop@11.0.11/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop@11.0.11/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop@11.0.11/java.awt.Window.dispatchEventImpl(Window.java:2784)
	at java.desktop@11.0.11/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop@11.0.11/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop@11.0.11/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop@11.0.11/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base@11.0.11/java.security.AccessController.doPrivileged(Native Method)
	at java.base@11.0.11/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base@11.0.11/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop@11.0.11/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop@11.0.11/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base@11.0.11/java.security.AccessController.doPrivileged(Native Method)
	at java.base@11.0.11/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop@11.0.11/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:886)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:815)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:752)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:442)
	at com.intellij.ide.IdeEventQueue$$Lambda$547/0x00000008006b2840.compute(Unknown Source)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:441)
	at com.intellij.ide.IdeEventQueue$$Lambda$546/0x00000008006b3840.run(Unknown Source)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:493)
	at java.desktop@11.0.11/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop@11.0.11/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop@11.0.11/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop@11.0.11/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop@11.0.11/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop@11.0.11/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by domjos1994** [comment]
I will update to a new Version
